version: "3.7"

services:
    make_my_change_front:
        image: node:20-alpine
        container_name: make_my_change_front
        working_dir: "/app"
        tty: true
        network_mode: host
        volumes:
            - .:/app
        ports:
            - 3001:3001
