version: "3.7"

services:
    make_my_change_front:
        image: node:20-alpine
        container_name: make_my_change_front
        working_dir: "/app"
        tty: true
        networks:
            - make_my_change_network
        volumes:
            - .:/app
        ports:
            - 3001:3001

networks:
    make_my_change_network:
        name: make_my_change_network
        external: true
