import { Mutable } from "../../_utils/mutable";

export class ProgrammingLanguage {

    protected static readonly OPTIONS = [
        "ANTLR",
        "ApacheConf",
        "Arduino",
        "ASP",
        "ASP.NET",
        "Assembly",
        "Astro",
        "Batchfile",
        "Blade",
        "C",
        "C#",
        "C++",
        "Cairo",
        "Clarity",
        "Classic ASP",
        "Clojure",
        "CMake",
        "Cobol",
        "CSS",
        "Cuda",
        "Dart",
        "Dockerfile",
        "EJS",
        "Elixir",
        "Erlang",
        "GAP",
        "Go",
        "Groovy",
        "Hack",
        "Handlebars",
        "Haskell",
        "HCL",
        "HTML",
        "Java",
        "JavaScript",
        "Jupyter Notebook",
        "Just",
        "Kotlin",
        "Lex",
        "Liquid",
        "LLVM",
        "Lua",
        "M4",
        "Makefile",
        "Matlab",
        "MATLAB",
        "MDX",
        "Move",
        "Nix",
        "NSIS",
        "Objective-C",
        "Objective-C++",
        "Pascal",
        "Pawn",
        "Perl",
        "PHP",
        "PLSQL",
        "PowerShell",
        "Processing",
        "Python",
        "R",
        "Roff",
        "Ruby",
        "Rust",
        "Sass",
        "Scala",
        "Scheme",
        "SCSS",
        "Shell",
        "Smarty",
        "Solidity",
        "SourcePawn",
        "SQL",
        "SQLPL",
        "Svelte",
        "Swift",
        "SWIG",
        "TeX",
        "TSQL",
        "Twig",
        "TypeScript",
        "Verilog",
        "Vim Script",
        "Visual Basic 6.0",
        "Vue",
        "XSLT",
        "Others",
    ] as const;

    public static readonly ValidValues = ProgrammingLanguage.OPTIONS as Mutable<typeof ProgrammingLanguage.OPTIONS>;

}
