import { Mutable } from '../../_utils/mutable';

export class ProgrammingLanguage {
  protected static readonly OPTIONS = [
    'ANTLR',
    'ApacheConf',
    'Arduino',
    'ASL',
    'ASP',
    'ASP.NET',
    'Assembly',
    'Astro',
    'Batchfile',
    'BitBake',
    'Blade',
    'C',
    'C#',
    'C++',
    'Cadence',
    'Cairo',
    'Clarity',
    'Classic ASP',
    'Clojure',
    'CMake',
    'Cobol',
    'CoffeeScript',
    'Common Lisp',
    'CSS',
    'Cuda',
    'CUE',
    'Cython',
    'Dart',
    'Dockerfile',
    'EJS',
    'Elixir',
    'Erlang',
    'Fortran',
    'GAP',
    'Gherkin',
    'GLSL',
    'Go',
    'Groovy',
    'Hack',
    'Handlebars',
    'Haskell',
    'HCL',
    'HLSL',
    'hoon',
    'HTML',
    'Java',
    'JavaScript',
    'Jinja',
    'Jupyter Notebook',
    'Just',
    'Kotlin',
    'Less',
    'Lex',
    'Liquid',
    'LLVM',
    'Lua',
    'M4',
    'Makefile',
    'Mako',
    'Matlab',
    'MATLAB',
    'MDX',
    'Meson',
    'Move',
    'Nix',
    'NSIS',
    'Nunjucks',
    'Objective-C',
    'Objective-C++',
    'Pascal',
    'Pawn',
    'Perl',
    'PHP',
    'PLpgSQL',
    'PLSQL',
    'PowerShell',
    'Processing',
    'Pug',
    'Python',
    'QMake',
    'QML',
    'R',
    'Ragel',
    'ReScript',
    'Roff',
    'RouterOS Script',
    'Ruby',
    'Rust',
    'Sass',
    'Scala',
    'Scheme',
    'SCSS',
    'Shell',
    'Slint',
    'Smarty',
    'Solidity',
    'SourcePawn',
    'SQL',
    'SQLPL',
    'Starlark',
    'Svelte',
    'Swift',
    'SWIG',
    'Tcl',
    'TeX',
    'Thrift',
    'TSQL',
    'Twig',
    'TypeScript',
    'VBA',
    'Verilog',
    'Vim Script',
    'Visual Basic',
    'Visual Basic 6.0',
    'Visual Basic .NET',
    'Vue',
    'Vyper',
    'WebAssembly',
    'XSLT',
    'Others',
  ] as const;

  public static readonly ValidValues = ProgrammingLanguage.OPTIONS as Mutable<
    typeof ProgrammingLanguage.OPTIONS
  >;
}
